[package]
name = "cps-standard-project"
version = "2.1.0"
entry = "examples/e1_hello.cpps"

[dependencies]
# Local path dependencies can be declared as:
# example = { path = "../example", version = "=1.0.0" }
